### ISSUE TITLE
Cut sequence places small dot at upper left and lower right corners of engraving area

### ISSUE THREAD

**Issue by mrsoftowl** [Makeblock-official/MLaser#1]
When attempting to cut out an image from a piece of paper, I noticed that the software puts a small dot at the upper left and lower right of the image. As I was trying to cut the material from a finished piece of paper, the dots are a problem.

**Comment by yangxuQZhit** [comment]
The small dot is used to located the image.We have reduced its influence in cutting and engraving, but it still exist.This problem may be solved in the future.
