### ISSUE TITLE
Current version verification, Check for Updates

### ISSUE THREAD

**Issue by mrsoftowl** [Makeblock-official/MLaser#2]
I am unable to determine the current version of the software I am running anywhere in the software. "Check for Updates" tries (and fails) to contact the host www.borunyouji.com. Please add a current version to the menu and fix the "Check for Updates" menu option.

**Comment by yangxuQZhit** [comment]
Thanks for your question.We'll fix the issue in the nest version, and you can find the current version number in the file (Config.ini),which is in the mlaser Installation directory.
