### ISSUE TITLE
Right click menu displays Chinese text instead of English

### ISSUE THREAD

**Issue by mrsoftowl** [Makeblock-official/MLaser#4]
When right clicking on items the menu reads in Chinese instead of English. I can assume the first item is about rotation, the others are unclear.

**Comment by Veda88** [comment]
Sounds like you are using version 1, which is still available [somewhere](http://www.makeblock.com/laserBot-robot-kit).
Download version 2.3 here: https://github.com/Makeblock-official/MLaser

This will also fix:
https://github.com/Makeblock-official/MLaser/issues/3
https://github.com/Makeblock-official/MLaser/issues/2 (well the check for updates, it still does not show what version you have installed)

For me (version 2.3) the current version can be found in: c:\Program Files (x86)\mLaser\Config.ini (open with text editor):
[update]
url=https://raw.githubusercontent.com/Makeblock-official/MLaser/master/Appcast.xml
version=2.3

**Comment by yangxuQZhit** [comment]
Some language issue has been solved in the version 2.3.
